import java.awt.*;

public class Colors {
    public static Color COMMANDS_COLOR = new Color(203, 119, 48);
    public static Color MAIN_FOREGROUND_COLOR = new Color(187, 187, 187);
    public static Color MAIN_BACKGROUND_COLOR = new Color(43, 43, 43);
    public static String[] PARSE_TABLE = new String[]{
            "adc ",
            "add ",
            "and ",
            "bsf ",
            "bsr ",
            "bt ",
            "btc ",
            "btr ",
            "bts ",
            "call ",
            "cbw ",
            "cld ",
            "clc ",
            "cli ",
            "cmc ",
            "cdq ",
            "cmp ",
            "cwd ",
            "cwde ",
            "dec ",
            "div ",
            "idiv ",
            "enter ",
            "imul ",
            "inc ",
            "jmp ",
            "lahe ",
            "leave ",
            "loop ",
            "loopnz ",
            "loopne ",
            "loopz ",
            "loope ",
            "mov ",
            "movsx ",
            "movzx ",
            "mul ",
            "neg ",
            "nop ",
            "not ",
            "or ",
            "pop ",
            "popa ",
            "popad ",
            "popf ",
            "popfd ",
            "push ",
            "pusha ",
            "pushad ",
            "pushf ",
            "pushfd ",
            "rcl ",
            "rcr ",
            "ret ",
            "retn ",
            "rete ",
            "rol ",
            "ror ",
            "sahe ",
            "sal ",
            "sar ",
            "sbb ",
            "shl ",
            "shld ",
            "shr ",
            "shrd",
            "stc",
            "std",
            "sti",
            "sub",
            "test",
            "xchg",
            "xor",
    };
}
